import React from "react";
import ReactDOM from "react-dom/client";

// Brand fonts (Geist Mono display + Inter body).
import "@fontsource-variable/geist-mono";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";

// Tokens: single source of truth, generated by Style Dictionary.
import "../../../packages/tokens/build/tokens.css";
import "./styles/global.css";
import "./styles/app.css";
import "./styles/onboarding.css";

import App from "./App";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
